### ISSUE TITLE
Auto-indentation madness.

### ISSUE THREAD

**Issue by Fiveside** [tht13/Python-vscode#14]
I'm experiencing some extraordinary behavior with the new auto-indentation feature.

![screencast-2016-02-09-164109](https://cloud.githubusercontent.com/assets/1858172/12935718/ccbc27e2-cf4c-11e5-818f-f8742865744a.gif)

Note that after typing `class Bar:` I'm not pressing any other keys.  That just happens by itself on the last line of the file

**Comment by tht13** [comment]
Thank you for reporting this, will be fixed promptly

**Comment by tht13** [comment]
Fixed in b6ac74ee 
v0.2.2 is now on the marketplace 
Thanks for reporting :+1:

**Comment by Fiveside** [comment]
Thank you!  This fixed the method parameter indentation weirdness and the infinite spacing problem.
