### ISSUE TITLE
debuger not working

### ISSUE THREAD

**Issue by boazdori** [tht13/Python-vscode#34]
Issue Type: <b>Bug</b>

when using the 1.26 version the debuger worked with 1.3 it stoped working tried reinstaling vs code didn't solve the issue

Extension version: 0.2.3
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.69GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by tht13** [comment]
This is probably intended for https://github.com/Microsoft/vscode-python
That is the python extension with the debugger, this extension only provides linting.
