### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by andricliu2015** [tht13/Python-vscode#36]
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `0.2.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by GitMensch** [comment]
@andricliu2015 please close this yourself - this issue is not useful at all as it has no content about an actual issue, just the version numbers
