### ISSUE TITLE
Indentation after newline when appropriate.

### ISSUE THREAD

**Issue by Raynes** [tht13/Python-vscode#5]
For example:

```python
if foo:
|
```

This is a travesty. I have to press one whole extra button before I can type code again! A tab, even! Way out of reach.

This is the current behavior because there is effectively no built in integration at the moment. Even something dumb like "after a `:\n` indent 4 spaces seems like it'd be better than the current state of things. :cry:

What I'd just :heart_eyes: to have is:

```python
if foo:
    |
```

amirite?

I'd do it myself but it's midnight on Sunday here in ol' Los Angeles and my coworkers likely expect me to show up for work in the morning and extensions seem fairly complicated, just getting into them. I'd love to help though. Gimme your thoughts, I'm gonna go set 3 alarms for 8AM and watch Supernatural until I die of cringy plotlines and :pray: for the best.

**Comment by tht13** [comment]
I agree it is definitely an annoyance right now. I think a regex should work but might fail on edge cases, but hopefully users like yourself will report when this occurs.
I'll work to add this in the next release :smile:

**Comment by bgse** [comment]
I'd vote for "indent user-defined number of spaces", just to avoid unnecessary bloodshed :+1:

**Comment by Raynes** [comment]
For consistency, I agree. On principle, screw anyone not using 4 space Python indents. :P

**Comment by tht13** [comment]
Vscode already has a preference setting for indentation size and spaces-or-tabs so using these would be the prefered option. Eliminate extra work for the user :+1: 
But i do agree forcing 4 spaces is tempting.... :wink:

**Comment by tht13** [comment]
Fixed in 1902f8a.
As promised it defaults to 4 spaces if not set in the editor.tabSize setting :smile:

**Comment by Raynes** [comment]
Thank you goodest of sirs.
