### ISSUE TITLE
Different linters.

### ISSUE THREAD

**Issue by Raynes** [tht13/Python-vscode#6]
I know it's a pain because there are a billion of them, but damn it bro I really love flake8 and I'd sure like to be able to use it the same way pylint is integrated in this guy. Also happy to help with that when I'm not sleep deprived.

Love your thoughts on this, and have a great :city_sunrise:!

**Comment by tht13** [comment]
Very interesting suggestion!
I haven't worked with other linters so am unsure of their output. I know in pylint you can specify a output template, if this is possible in others (such as flake8) then this would be a great addition and should not be too difficult. 
I would definitely appreciate help with this :smile: 
User choice is always best :+1:

**Comment by tht13** [comment]
I have had a quick look at the documentation for flake8 and this is definitely possible and I think should be done :smile: 
To do this though I think it would be best to slightly redesign the server side to make it more modular so linters like these can be used on an almost plug and play basis.

**Comment by Raynes** [comment]
Flake8 is the bombshizzle, excited to see folks excited. I'll try to find some time to help out!

**Comment by tht13** [comment]
Prep for this has been done in 7303d67 
Code has been refactored to allow extension of the [`BaseLinter`](https://github.com/tht13/Python-vscode/blob/95e97cea80865fc0732d9dfeae8903fc8cfd924b/src/server/src/linter/baseLinter.ts#L6) class to provide choice of linters.

still TODO
 - [ ] add other linters (i.e Flake8)
 - [ ] Add setting in user preferences for choice of linter

**Comment by tht13** [comment]
Feature completed in fc11f8d2.
